// app/routes/blog/index.tsx
import { Link, LoaderFunction, useLoaderData } from "remix";
import { PageSection, Heading } from "~/components";
import { load } from "~/datocms/datocms";

type Blog = {
  title: string;
  date: string;
  excerpt: string;
  id: number;
  slug: string;
};

const BLOGS_QUERY = `
  query BlogsQuery {
    allArticles(orderBy: _createdAt_DESC) {
      title
      date
      excerpt
      id
      slug
    }
  }
`;

export const loader: LoaderFunction = ({ context }) => {
  return load({
    query: BLOGS_QUERY,
    variables: { limit: 10 },
    token: context.DATOCMS_READONLY_TOKEN,
  });
};

export default function Blog() {
  const { allArticles } = useLoaderData<{ allArticles: Blog[] }>();

  return (
    <PageSection>
      <Heading level="1" classNames="text-highlight">
        Blog
      </Heading>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-x-10 gap-y-14">
        {allArticles.map((blog) => (
          <article key={blog.id} className="flex flex-col">
            <h2 className="font-bold text-lg">
              <Link to={`/blog/${blog.slug}`} prefetch="intent">
                {blog.title}
              </Link>
            </h2>
            <p className="mb-4 opacity-50">{blog.excerpt}</p>
            <footer className="flex items-end flex-1">
              <div className="flex-1 flex justify-between">
                <time dateTime={blog.date}>
                  {new Intl.DateTimeFormat("en-US", {
                    dateStyle: "medium",
                  }).format(new Date(blog.date) as unknown as Date)}
                </time>
                <Link to={`/blog/${blog.slug}`} prefetch="intent">
                  read more &rarr;
                </Link>
              </div>
            </footer>
          </article>
        ))}
      </div>
    </PageSection>
  );
}

// src/routes/blog/index.svelte
<script context="module">
	/**
	 * @type {import('@sveltejs/kit').Load}
	 */
	export async function load({ fetch }) {
		const posts = await fetch('/blog.json').then((res) => res.json());
		return {
			props: {
				posts
			}
		};
	}
</script>

<script>
	import Title from '../../components/PageTitle.svelte';
	export let posts;
</script>

<Title title={'Blog'} />

<h1 class="text-4xl font-bold mb-4">Blog</h1>

<div class="max-w-xl flex flex-col gap-4">
	{#each posts as { title, description, slug, date }}
		<article>
			<h2 class="text-lg font-semibold">{title}</h2>
			<time datetime={date} class="text-sm text-gray-500 block mb-2 xl:text-md"
				>{new Intl.DateTimeFormat('en-US', { dateStyle: 'full' }).format(new Date(date))}</time
			>
			<p class="text-gray-500 mb-3">{description}</p>
			<footer>
				<a href={`/blog/${slug}`} class="text-sm text-blue-500 hover:text-blue-700 duration-150"
					>Read more &rarr;</a
				>
			</footer>
		</article>
	{/each}
</div>
